---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: quay.io/coreos/jsonnet-ci
  commands:
  - find . -type f -not -path './vendor/*' \( -name '*.libsonnet' -o -name '*.jsonnet' \) | xargs -L1 jsonnetfmt --test
  - jb install
  - ./build.sh
  - git diff --exit-code
