apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jaeger-all-in-one
  name: jaeger-all-in-one
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-all-in-one
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger-all-in-one
    spec:
      containers:
      - args:
        - --badger.directory-key=/var/jaeger/store/keys
        - --badger.directory-value=/var/jaeger/store/values
        - --badger.ephemeral=false
        env:
        - name: SPAN_STORAGE_TYPE
          value: badger
        image: jaegertracing/all-in-one:1.14.0
        name: jaeger-all-in-one
        ports:
        - containerPort: 14250
          name: grpc
        - containerPort: 14269
          name: admin-http
        - containerPort: 16686
          name: query
        volumeMounts:
        - mountPath: /var/jaeger/store
          name: jaeger-store-data
          readOnly: false
      volumes:
      - name: jaeger-store-data
        persistentVolumeClaim:
          claimName: jaeger-store-data
