apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
  namespace: observability-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - args:
        - query
        - --query.replica-label=replica
        - --store=dnssrv+thanos-store.observability-platform.svc.cluster.local:10901
        - --store=dnssrv+thanos-receive.observability-platform.svc.cluster.local:10901
        image: improbable/thanos:v0.5.0
        name: thanos-querier
