apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
  namespace: observatorium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - args:
        - query
        - --query.replica-label=replica
        - --store=dnssrv+_grpc._tcp.thanos-store.observatorium.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive.observatorium.svc.cluster.local
        image: improbable/thanos:v0.6.0-rc.0
        name: thanos-querier
