apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receive
    controller.receive.thanos.io: thanos-receive-controller
  name: thanos-receive
  namespace: observatorium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-receive
      controller.receive.thanos.io: thanos-receive-controller
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
        controller.receive.thanos.io: thanos-receive-controller
    spec:
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/tsdb
        - --labels=replica="$(NAME)"
        - --labels=receive="true"
        - --tsdb.retention=6h
        - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        image: improbable/thanos:v0.6.0-rc.0
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        volumeMounts:
        - mountPath: /var/thanos/tsdb
          name: data
          readOnly: false
        - mountPath: /var/lib/thanos-receive
          name: observatorium-tenants
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: observatorium-tenants-generated
        name: observatorium-tenants
  volumeClaimTemplates: []
