jobs:
  build:
    working_directory: /go/src/github.com/observatorium/configuration
    docker:
      - image: quay.io/coreos/jsonnet-ci
    steps:
      - checkout
      - run: find . -type f -not -path './vendor/*' \( -name '*.libsonnet' -o -name '*.jsonnet' \) | xargs -L1 jsonnetfmt --test
      - run: curl -o ./jb -L "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.2.0/jb-$(go env GOOS)-$(go env GOARCH)" && chmod +x ./jb
      - run: ./jb install
      - run: ./build.sh
      - run: git diff --exit-code

  tests:
    machine: true
    steps:
      - checkout
      - run: |
          ./tests/kind.sh
          ./tests/deploy.sh
          ./tests/test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tests
