jobs:
  build:
    working_directory: /go/src/github.com/observatorium/observatorium
    docker:
      - image: quay.io/coreos/jsonnet-ci
    steps:
      - checkout
      - run: make fmt
      - run: make generate-cert
      - run: make generate deployments/tests/manifests
      - run: git diff --exit-code -- . ':(exclude)deployments/tests/manifests/observatorium-xyz-tls-secret.yaml' ':(exclude)deployments/tests/manifests/observatorium-xyz-tls-configmap.yaml' ':(exclude)deployments/tests/manifests/observatorium-xyz-tls-dex.yaml' ':(exclude)deployments/tests/manifests/test-ca-tls.yaml'
      - run: make validate

  tests:
    machine: true
    steps:
      - checkout
      - run:
          name: e2e tests
          no_output_timeout: 30m
          command : |
            ./deployments/tests/e2e.sh kind
            ./deployments/tests/e2e.sh deploy
            ./deployments/tests/e2e.sh test
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  test-and-push:
    jobs:
      - build
      - tests
