apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: observatorium-xyz-api-gateway
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-02-13-adfef4b5
  name: observatorium-xyz-observatorium-api-gateway-thanos-query
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium-xyz-api-gateway
      app.kubernetes.io/name: thanos-query
      app.kubernetes.io/part-of: observatorium
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-layer
        app.kubernetes.io/instance: observatorium-xyz-api-gateway
        app.kubernetes.io/name: thanos-query
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: master-2020-02-13-adfef4b5
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - thanos-query
              namespaces:
              - observatorium
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --web.external-prefix=/ui/v1/metrics
        image: quay.io/thanos/thanos:master-2020-02-13-adfef4b5
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          periodSeconds: 30
        name: thanos-query
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120
